title: Param Aggarwal
description: Software engineer with a design-obsessed mind living in Bangalore, India.
google_analytics: UA-81674684-1
show_downloads: false
remote_theme: sharu725/online-cv

name: Param Aggarwal
tagline: Software engineer with a design-obsessed mind living in Bangalore, India.

email: paramaggarwal@gmail.com
website: medium.com/@paramaggarwal
linkedin: paramaggarwal
github: paramaggarwal
twitter: '@paramaggarwal'

gems:
  - jekyll-mentions
