name: Param Aggarwal
tagline: Cross-platform front-end apps at Flipkart in React and React Native. Deletionist.
pic: profile.jpg
url: 'http://paramaggarwal.com'

analytics: UA-81674684-1

plugins:
  - jekyll-mentions
