title: Param Aggarwal
description: Software Product Engineer. Develops Web and Mobile Apps. Previously, React and React Native at Myntra.Deep Learning. Robotics. Web and Mobile Apps. Formerly worked with React and React Native at Myntra.
google_analytics: UA-81674684-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
