title: Param Aggarwal
description: Self-driving Car Engineering Student. Worked on React & React Native based apps, played with Arduino and ESP8266 based hardware. 26. Lives near Mumbai, India.
google_analytics: UA-81674684-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
