title: Param Aggarwal
description: Software engineer with a design-obsessed mind living in Bangalore, India.
google_analytics: UA-81674684-1
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
