title: Param Aggarwal
description: Web and iOS Developer with a preference for React and React Native. Thinker and occasional builder. 26. Lives in Thane, Mumbai, India.
google_analytics: UA-81674684-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
