title: Param Aggarwal
description: Software Product Engineer. Develops Web and Mobile Apps using React and React Native.
google_analytics: UA-81674684-1
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
